version: '3.0'
services:
    app: 
        image: showwin/phoenix:1.5.9
        command: mix phx.server
        working_dir: /app
        volumes:
            - .:/app:cached
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DATABASE=todo_app
            - POSTGRES_HOSTNAME=db
        ports:
            - "4000:4000"
        links:
            - db
    db:
        image: postgres:13.3
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=docker
          - POSTGRES_DB=todo_app
        ports:
            - 5432:5432
        volumes:
          - storage:/var/lib/postgresql/
volumes:
    storage:
